sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t mahnkong/docker-rpimpd .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=latest
    docker tag mahnkong/docker-rpimpd mahnkong/docker-rpimpd:$TAG
    docker push mahnkong/docker-rpimpd:$TAG
    docker push mahnkong/docker-rpimpd
  fi
